export {
  type RealtimeEventPayload,
  type RealtimeEventHandler,
  type ReconnectHandler,
  createNotificationHubConnection,
  createChatHubConnection,
  startConnection,
  stopConnection,
  onRealtimeEvent,
  joinGroup,
  leaveGroup,
  isDuplicate,
  registerReconnectHandler,
  fireReconnect,
  registerNotificationGroup,
  registerChatGroup,
  rejoinAllNotificationGroups,
  rejoinAllChatGroups,
  getActiveNotificationGroups,
  getActiveChatGroups,
  getNotificationGroupRefCount,
  getChatGroupRefCount,
} from "./signalrClient";

export {
  useRealtimeNotifications,
  useRealtimeChat,
  useJoinMarket,
  useJoinLayout,
  useJoinBooth,
  useJoinSupportTicket,
  useJoinConversation,
  useOnReconnect,
} from "./useRealtime";
