"use client";

import { useEffect, useMemo, useState } from "react";
import { ChevronLeft, MessageSquare, Star, X } from "lucide-react";
import { useBooth } from "@/application/context/BoothContext";
import { reviewService } from "@/application/features/reviews/reviewService";
import type { Review } from "@/shared/types";
import { Pagination } from "./Pagination";

export function Reviews() {
  const { selectedBooth } = useBooth();
  const [reviews, setReviews] = useState<Review[]>([]);
  const [loading, setLoading] = useState(false);
  const [ratingFilter, setRatingFilter] = useState("All");
  const [replyFilter, setReplyFilter] = useState("All");
  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage, setItemsPerPage] = useState(10);
  const [detail, setDetail] = useState<Review | null>(null);
  const [reply, setReply] = useState("");
  const [saving, setSaving] = useState(false);

  const [error, setError] = useState("");

  useEffect(()=>{ if(!selectedBooth?.id){setReviews([]);return;} let active=true; setLoading(true); setError(""); reviewService.getByBooth(selectedBooth.id,1,100).then((res)=>{if(active)setReviews(res.data.items??[]);}).catch(()=>{if(active) { setError("Failed to load reviews."); setReviews([]); }}).finally(()=>{if(active)setLoading(false);}); return()=>{active=false;}; },[selectedBooth?.id]);
  const filtered=useMemo(()=>reviews.filter((review)=>{const rating=ratingFilter==="All"||review.rating===Number(ratingFilter); const replied=Boolean(review.reply); const replyMatch=replyFilter==="All"||(replyFilter==="Needs Reply"&&!replied)||(replyFilter==="Replied"&&replied); return rating&&replyMatch;}),[reviews,ratingFilter,replyFilter]);
  const visible=filtered.slice((currentPage-1)*itemsPerPage,currentPage*itemsPerPage);
  const saveReply=async()=>{if(!detail||!reply.trim())return; setSaving(true); setError(""); try{const result=await reviewService.reply(detail.id,reply.trim()); setReviews((items)=>items.map((item)=>item.id===detail.id?result.data:item)); setDetail(result.data); setReply("");}catch{ setError("Failed to submit reply."); }finally{setSaving(false);}};

  if(detail){return <div className="p-8 pb-12 max-w-5xl mx-auto space-y-6"><button onClick={()=>setDetail(null)} className="inline-flex items-center gap-2 text-sm font-medium text-gray-600 hover:text-indigo-600"><ChevronLeft className="w-4 h-4" /> Back to Reviews</button>{error && <div className="p-4 bg-red-50 text-red-600 rounded-lg flex justify-between">{error}<button onClick={()=>setError("")}><X className="w-4 h-4"/></button></div>}<div className="bg-white rounded-xl border border-gray-200 shadow-[0_1px_4px_rgba(0,0,0,0.08)] overflow-hidden"><div className="px-6 py-5 border-b border-gray-100 flex items-start justify-between"><div><p className="text-xs font-bold text-indigo-600">Order {detail.orderCode || "Not available"}</p><h2 className="text-lg font-bold text-gray-900 mt-1">Customer {detail.customerName || "Not available"}</h2><div className="flex gap-0.5 mt-2">{Array.from({length:5},(_,i)=><Star key={i} className={`w-4 h-4 ${i<detail.rating?"fill-amber-400 text-amber-400":"text-gray-200"}`} />)}</div></div><button onClick={()=>setDetail(null)} className="p-2 text-gray-400 hover:bg-gray-100 rounded-lg"><X className="w-5 h-5" /></button></div><div className="p-6 space-y-5"><div><h3 className="text-sm font-bold text-gray-900 uppercase">Review</h3><p className="text-sm text-gray-600 mt-2">{detail.content||"No data available"}</p></div>{detail.imageUrl&&<img src={detail.imageUrl} alt="Customer review" className="max-h-64 rounded-lg object-cover" />}<div><h3 className="text-sm font-bold text-gray-900 uppercase mb-3">Booth Reply</h3>{detail.reply?<div className="bg-indigo-50 rounded-lg p-4 text-sm text-indigo-900">{detail.reply.content}</div>:<div className="flex gap-3"><input value={reply} onChange={(event)=>setReply(event.target.value)} placeholder="Write a reply..." className="flex-1 border border-gray-200 rounded-lg px-3 py-2.5 text-sm outline-none focus:border-indigo-500" /><button disabled={saving||!reply.trim()} onClick={saveReply} className="px-4 py-2.5 bg-indigo-600 disabled:bg-gray-300 text-white rounded-lg text-sm font-medium">Reply</button></div>}</div></div></div></div>}

  return <div className="p-8 pb-12 max-w-7xl mx-auto space-y-6">{error && !detail && <div className="p-4 bg-red-50 text-red-600 rounded-lg flex justify-between">{error}<button onClick={()=>setError("")}><X className="w-4 h-4"/></button></div>}<div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h2 className="text-2xl font-bold text-gray-900">Reviews</h2><p className="text-sm text-gray-500 mt-1">Read customer feedback and reply to reviews</p></div><div className="flex gap-3"><select value={ratingFilter} onChange={(event)=>{setRatingFilter(event.target.value);setCurrentPage(1);}} className="border border-gray-200 rounded-lg px-3 py-2 text-sm bg-white"><option>All</option>{[5,4,3,2,1].map((rating)=><option key={rating} value={rating}>{rating} stars</option>)}</select><select value={replyFilter} onChange={(event)=>{setReplyFilter(event.target.value);setCurrentPage(1);}} className="border border-gray-200 rounded-lg px-3 py-2 text-sm bg-white"><option>All</option><option>Needs Reply</option><option>Replied</option></select></div></div><div className="bg-white rounded-xl border border-gray-200 shadow-[0_1px_4px_rgba(0,0,0,0.08)] overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-gray-50 text-gray-500"><tr><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Order</th><th className="px-5 py-3">Rating</th><th className="px-5 py-3">Review</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-gray-100">{visible.length===0?<tr><td colSpan={6} className="px-5 py-14 text-center text-gray-400"><Star className="w-10 h-10 mx-auto mb-3 text-gray-200" />{loading?"Loading...":"No data available"}</td></tr>:visible.map((review)=><tr key={review.id} onClick={()=>setDetail(review)} className="cursor-pointer hover:bg-gray-50"><td className="px-5 py-4 font-semibold text-gray-900">{review.customerName || "Not available"}</td><td className="px-5 py-4 text-indigo-600">{review.orderCode || "Not available"}</td><td className="px-5 py-4"><span className="inline-flex items-center gap-1 font-bold"><Star className="w-4 h-4 fill-amber-400 text-amber-400" />{review.rating}</span></td><td className="px-5 py-4 max-w-[240px] truncate">{review.content||"No content"}</td><td className="px-5 py-4"><span className={`px-2.5 py-1 rounded-full text-xs font-semibold ${review.reply?"bg-emerald-100 text-emerald-700":"bg-amber-100 text-amber-700"}`}>{review.reply?"Replied":"Needs Reply"}</span></td><td className="px-5 py-4 text-right text-indigo-600"><MessageSquare className="w-4 h-4 ml-auto" /></td></tr>)}</tbody></table><Pagination currentPage={currentPage} totalItems={filtered.length} itemsPerPage={itemsPerPage} onPageChange={setCurrentPage} onItemsPerPageChange={(size)=>{setItemsPerPage(size);setCurrentPage(1);}} /></div></div>;
}
